package gui;

import controller.Controller;
import java.awt.Graphics;
import java.util.List;
import javax.swing.JLabel;
import java.awt.Image;
import model.*;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

public class MainFrame extends javax.swing.JFrame {

    private Controller controller;

    public MainFrame() {
        
        initComponents();
        setBackgroundImage();
        init();
    }

    private void setBackgroundImage() {
        backgroundLabel.setIcon(new javax.swing.ImageIcon("img/background.jpeg"));
        backgroundLabel.setPreferredSize(new java.awt.Dimension(2500, 1200));
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 2500, 1200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRandom1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonEnter1 = new javax.swing.JButton();
        jButtonRandom2 = new javax.swing.JButton();
        jButtonEnter2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonRandom3 = new javax.swing.JButton();
        jButtonEnter3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonRandom4 = new javax.swing.JButton();
        jButtonEnter4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonRandom5 = new javax.swing.JButton();
        jButtonEnter5 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButtonRandom6 = new javax.swing.JButton();
        jButtonEnter6 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldBoard = new javax.swing.JTextField();
        jButtonEnterBoard = new javax.swing.JButton();
        jButtonBoardRandom = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonCalculate = new javax.swing.JButton();
        jButtonFold1 = new javax.swing.JButton();
        jButtonFold2 = new javax.swing.JButton();
        jButtonFold3 = new javax.swing.JButton();
        jButtonFold4 = new javax.swing.JButton();
        jButtonFold5 = new javax.swing.JButton();
        jButtonFold6 = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();
        jLbelJ1 = new javax.swing.JLabel();
        jLabelJ1C1 = new javax.swing.JLabel();
        jLabelJ1C2 = new javax.swing.JLabel();
        jLabelEquity1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelJ2C1 = new javax.swing.JLabel();
        jLabelJ2C2 = new javax.swing.JLabel();
        jLabelEquity2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelJ6C1 = new javax.swing.JLabel();
        jLabelJ6C2 = new javax.swing.JLabel();
        jLabelEquity6 = new javax.swing.JLabel();
        jLabelBoardC1 = new javax.swing.JLabel();
        jLabelBoardC2 = new javax.swing.JLabel();
        jLabelBoardC3 = new javax.swing.JLabel();
        jLabelBoardC5 = new javax.swing.JLabel();
        jLabelBoardC4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelJ3C1 = new javax.swing.JLabel();
        jLabelJ3C2 = new javax.swing.JLabel();
        jLabelEquity3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelJ5C1 = new javax.swing.JLabel();
        jLabelJ5C2 = new javax.swing.JLabel();
        jLabelEquity5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelJ4C1 = new javax.swing.JLabel();
        jLabelJ4C2 = new javax.swing.JLabel();
        jLabelEquity4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1040, 800));
        getContentPane().setLayout(null);

        jButtonRandom1.setText("Random");
        jButtonRandom1.setToolTipText("");
        jButtonRandom1.setFocusPainted(false);
        jButtonRandom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandom1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRandom1);
        jButtonRandom1.setBounds(305, 550, 75, 23);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jugador1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(81, 553, 54, 16);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(141, 550, 71, 22);

        jButtonEnter1.setText("Enter");
        jButtonEnter1.setFocusPainted(false);
        jButtonEnter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnter1);
        jButtonEnter1.setBounds(218, 550, 81, 23);

        jButtonRandom2.setText("Random");
        jButtonRandom2.setFocusPainted(false);
        jButtonRandom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandom2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRandom2);
        jButtonRandom2.setBounds(305, 579, 75, 23);

        jButtonEnter2.setText("Enter");
        jButtonEnter2.setFocusPainted(false);
        jButtonEnter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnter2);
        jButtonEnter2.setBounds(218, 579, 81, 23);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(141, 579, 71, 22);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jugador2");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(81, 582, 54, 16);

        jButtonRandom3.setText("Random");
        jButtonRandom3.setFocusPainted(false);
        jButtonRandom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandom3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRandom3);
        jButtonRandom3.setBounds(305, 608, 75, 23);

        jButtonEnter3.setText("Enter");
        jButtonEnter3.setFocusPainted(false);
        jButtonEnter3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnter3);
        jButtonEnter3.setBounds(218, 608, 81, 23);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(141, 607, 71, 22);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jugador3");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(81, 610, 54, 16);

        jButtonRandom4.setText("Random");
        jButtonRandom4.setFocusPainted(false);
        jButtonRandom4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandom4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRandom4);
        jButtonRandom4.setBounds(700, 550, 75, 23);

        jButtonEnter4.setText("Enter");
        jButtonEnter4.setFocusPainted(false);
        jButtonEnter4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnter4);
        jButtonEnter4.setBounds(613, 550, 81, 23);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(536, 550, 71, 22);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jugador4");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(476, 553, 54, 16);

        jButtonRandom5.setText("Random");
        jButtonRandom5.setFocusPainted(false);
        jButtonRandom5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandom5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRandom5);
        jButtonRandom5.setBounds(700, 579, 75, 23);

        jButtonEnter5.setText("Enter");
        jButtonEnter5.setFocusPainted(false);
        jButtonEnter5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnter5);
        jButtonEnter5.setBounds(613, 579, 81, 23);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(536, 579, 71, 22);

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Jugador5");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(476, 582, 54, 16);

        jButtonRandom6.setText("Random");
        jButtonRandom6.setFocusPainted(false);
        jButtonRandom6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandom6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRandom6);
        jButtonRandom6.setBounds(700, 608, 75, 23);

        jButtonEnter6.setText("Enter");
        jButtonEnter6.setFocusPainted(false);
        jButtonEnter6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnter6);
        jButtonEnter6.setBounds(613, 608, 81, 23);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(536, 608, 71, 22);

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Jugador6");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(476, 611, 54, 16);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("board");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(326, 652, 42, 16);

        jTextFieldBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBoardActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldBoard);
        jTextFieldBoard.setBounds(374, 649, 71, 22);

        jButtonEnterBoard.setText("Enter");
        jButtonEnterBoard.setFocusPainted(false);
        jButtonEnterBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBoardEnterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnterBoard);
        jButtonEnterBoard.setBounds(451, 649, 83, 23);

        jButtonBoardRandom.setText("Random");
        jButtonBoardRandom.setFocusPainted(false);
        jButtonBoardRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBoardRandomActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBoardRandom);
        jButtonBoardRandom.setBounds(540, 649, 75, 23);

        jButtonClear.setText("Clear");
        jButtonClear.setFocusPainted(false);
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClear);
        jButtonClear.setBounds(879, 616, 88, 32);

        jButtonCalculate.setText("Calculate");
        jButtonCalculate.setFocusPainted(false);
        jButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculateActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalculate);
        jButtonCalculate.setBounds(879, 565, 88, 33);

        jButtonFold1.setFocusPainted(false);
        jButtonFold1.setLabel("fold");
        jButtonFold1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFold1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFold1);
        jButtonFold1.setBounds(386, 550, 72, 23);

        jButtonFold2.setFocusPainted(false);
        jButtonFold2.setLabel("fold");
        jButtonFold2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFold2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFold2);
        jButtonFold2.setBounds(386, 579, 72, 23);

        jButtonFold3.setFocusPainted(false);
        jButtonFold3.setLabel("fold");
        jButtonFold3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFold3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFold3);
        jButtonFold3.setBounds(386, 608, 72, 23);

        jButtonFold4.setFocusPainted(false);
        jButtonFold4.setLabel("fold");
        jButtonFold4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFold4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFold4);
        jButtonFold4.setBounds(781, 550, 72, 23);

        jButtonFold5.setFocusPainted(false);
        jButtonFold5.setLabel("fold");
        jButtonFold5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFold5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFold5);
        jButtonFold5.setBounds(781, 579, 72, 23);

        jButtonFold6.setFocusPainted(false);
        jButtonFold6.setLabel("fold");
        jButtonFold6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFold6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFold6);
        jButtonFold6.setBounds(781, 608, 72, 23);

        backgroundLabel.setText("jLabel11");
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 43, 16);

        jLbelJ1.setForeground(new java.awt.Color(255, 255, 255));
        jLbelJ1.setText("Jugador1");
        getContentPane().add(jLbelJ1);
        jLbelJ1.setBounds(330, 40, 60, 16);
        getContentPane().add(jLabelJ1C1);
        jLabelJ1C1.setBounds(290, 70, 64, 79);
        getContentPane().add(jLabelJ1C2);
        jLabelJ1C2.setBounds(360, 70, 64, 79);

        jLabelEquity1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEquity1.setText("0,00%");
        getContentPane().add(jLabelEquity1);
        jLabelEquity1.setBounds(340, 160, 58, 24);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jugador2");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(620, 40, 60, 16);
        getContentPane().add(jLabelJ2C1);
        jLabelJ2C1.setBounds(580, 70, 64, 79);
        getContentPane().add(jLabelJ2C2);
        jLabelJ2C2.setBounds(650, 70, 64, 79);

        jLabelEquity2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEquity2.setText("0,00%");
        getContentPane().add(jLabelEquity2);
        jLabelEquity2.setBounds(630, 160, 58, 24);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jugador6");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 200, 60, 16);
        getContentPane().add(jLabelJ6C1);
        jLabelJ6C1.setBounds(60, 230, 64, 79);
        getContentPane().add(jLabelJ6C2);
        jLabelJ6C2.setBounds(130, 230, 64, 79);

        jLabelEquity6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEquity6.setText("0,00%");
        getContentPane().add(jLabelEquity6);
        jLabelEquity6.setBounds(110, 320, 58, 24);
        getContentPane().add(jLabelBoardC1);
        jLabelBoardC1.setBounds(320, 230, 64, 79);
        getContentPane().add(jLabelBoardC2);
        jLabelBoardC2.setBounds(390, 230, 64, 79);
        getContentPane().add(jLabelBoardC3);
        jLabelBoardC3.setBounds(460, 230, 64, 79);
        getContentPane().add(jLabelBoardC5);
        jLabelBoardC5.setBounds(530, 230, 64, 79);
        getContentPane().add(jLabelBoardC4);
        jLabelBoardC4.setBounds(600, 230, 64, 79);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jugador3");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(850, 200, 60, 16);
        getContentPane().add(jLabelJ3C1);
        jLabelJ3C1.setBounds(810, 230, 64, 79);
        getContentPane().add(jLabelJ3C2);
        jLabelJ3C2.setBounds(880, 230, 64, 79);

        jLabelEquity3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEquity3.setText("0,00%");
        getContentPane().add(jLabelEquity3);
        jLabelEquity3.setBounds(860, 320, 58, 24);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jugador5");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 370, 60, 16);
        getContentPane().add(jLabelJ5C1);
        jLabelJ5C1.setBounds(290, 400, 64, 79);
        getContentPane().add(jLabelJ5C2);
        jLabelJ5C2.setBounds(360, 400, 64, 79);

        jLabelEquity5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEquity5.setText("0,00%");
        getContentPane().add(jLabelEquity5);
        jLabelEquity5.setBounds(340, 490, 58, 24);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jugador4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(620, 370, 60, 16);
        getContentPane().add(jLabelJ4C1);
        jLabelJ4C1.setBounds(580, 400, 64, 79);
        getContentPane().add(jLabelJ4C2);
        jLabelJ4C2.setBounds(650, 400, 64, 79);

        jLabelEquity4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEquity4.setText("0,00%");
        getContentPane().add(jLabelEquity4);
        jLabelEquity4.setBounds(630, 490, 58, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        ImageIcon icon = new ImageIcon("img/back.png");
        jLabelJ1C1.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ1C2.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ2C1.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ2C2.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ3C1.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ3C2.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ4C1.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ4C2.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ5C1.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ5C2.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ6C1.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ6C2.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelBoardC1.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelBoardC2.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelBoardC3.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelBoardC4.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelBoardC5.setIcon(resizeImage(icon.getImage(), 64, 79));
    }
    private void jButtonRandom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandom1ActionPerformed
        // TODO add your handling code here:
        this.controller.randomJugCard(0);
        List<Carta> carta = this.controller.getJugadorCarta(0);
        ImageIcon icon1 = new ImageIcon("img/" + carta.get(0).toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta.get(1).toString() + ".png");

        jLabelJ1C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ1C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom1.setEnabled(false);
        jTextField1.setEnabled(false);
        jButtonEnter1.setEnabled(false);
    }//GEN-LAST:event_jButtonRandom1ActionPerformed

    private void jButtonEnter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter1ActionPerformed
        // TODO add your handling code here:
        controller.enterJugCard(0, jTextField1.getText());
        Carta carta1 = this.controller.getJugadorCarta(0).get(0);
        Carta carta2 = this.controller.getJugadorCarta(0).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ1C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ1C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom1.setEnabled(false);
        jTextField1.setEnabled(false);
        jButtonEnter1.setEnabled(false);

    }//GEN-LAST:event_jButtonEnter1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonRandom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandom2ActionPerformed
        // TODO add your handling code here:
        this.controller.randomJugCard(1);
        Carta carta1 = this.controller.getJugadorCarta(1).get(0);
        Carta carta2 = this.controller.getJugadorCarta(1).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ2C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ2C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom2.setEnabled(false);
        jTextField2.setEnabled(false);
        jButtonEnter2.setEnabled(false);
    }//GEN-LAST:event_jButtonRandom2ActionPerformed

    private void jButtonEnter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter2ActionPerformed
        // TODO add your handling code here:
        controller.enterJugCard(1, jTextField2.getText());
        Carta carta1 = this.controller.getJugadorCarta(1).get(0);
        Carta carta2 = this.controller.getJugadorCarta(1).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ2C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ2C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom2.setEnabled(false);
        jTextField2.setEnabled(false);
        jButtonEnter2.setEnabled(false);
    }//GEN-LAST:event_jButtonEnter2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButtonRandom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandom3ActionPerformed
        // TODO add your handling code here:
        this.controller.randomJugCard(2);
        Carta carta1 = this.controller.getJugadorCarta(2).get(0);
        Carta carta2 = this.controller.getJugadorCarta(2).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ3C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ3C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom3.setEnabled(false);
        jTextField3.setEnabled(false);
        jButtonEnter3.setEnabled(false);
    }//GEN-LAST:event_jButtonRandom3ActionPerformed

    private void jButtonEnter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter3ActionPerformed
        // TODO add your handling code here:
        controller.enterJugCard(2, jTextField3.getText());
        Carta carta1 = this.controller.getJugadorCarta(2).get(0);
        Carta carta2 = this.controller.getJugadorCarta(2).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ3C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ3C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom3.setEnabled(false);
        jTextField3.setEnabled(false);
        jButtonEnter3.setEnabled(false);
    }//GEN-LAST:event_jButtonEnter3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButtonRandom4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandom4ActionPerformed
        // TODO add your handling code here:
        this.controller.randomJugCard(3);
        Carta carta1 = this.controller.getJugadorCarta(3).get(0);
        Carta carta2 = this.controller.getJugadorCarta(3).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ4C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ4C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom4.setEnabled(false);
        jTextField4.setEnabled(false);
        jButtonEnter4.setEnabled(false);
    }//GEN-LAST:event_jButtonRandom4ActionPerformed

    private void jButtonEnter4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter4ActionPerformed
        // TODO add your handling code here:
        controller.enterJugCard(3, jTextField4.getText());
        Carta carta1 = this.controller.getJugadorCarta(3).get(0);
        Carta carta2 = this.controller.getJugadorCarta(3).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ4C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ4C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom4.setEnabled(false);
        jTextField4.setEnabled(false);
        jButtonEnter4.setEnabled(false);
    }//GEN-LAST:event_jButtonEnter4ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButtonRandom5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandom5ActionPerformed
        // TODO add your handling code here:
        this.controller.randomJugCard(4);
        Carta carta1 = this.controller.getJugadorCarta(4).get(0);
        Carta carta2 = this.controller.getJugadorCarta(4).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ5C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ5C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom5.setEnabled(false);
        jTextField5.setEnabled(false);
        jButtonEnter5.setEnabled(false);
    }//GEN-LAST:event_jButtonRandom5ActionPerformed

    private void jButtonEnter5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter5ActionPerformed
        // TODO add your handling code here:
        controller.enterJugCard(4, jTextField5.getText());
        Carta carta1 = this.controller.getJugadorCarta(4).get(0);
        Carta carta2 = this.controller.getJugadorCarta(4).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ5C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ5C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom5.setEnabled(false);
        jTextField5.setEnabled(false);
        jButtonEnter5.setEnabled(false);
    }//GEN-LAST:event_jButtonEnter5ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButtonRandom6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandom6ActionPerformed
        // TODO add your handling code here:
        this.controller.randomJugCard(5);
        Carta carta1 = this.controller.getJugadorCarta(5).get(0);
        Carta carta2 = this.controller.getJugadorCarta(5).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ6C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ6C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom6.setEnabled(false);
        jTextField6.setEnabled(false);
        jButtonEnter6.setEnabled(false);
    }//GEN-LAST:event_jButtonRandom6ActionPerformed

    private void jButtonEnter6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter6ActionPerformed
        // TODO add your handling code here:
        controller.enterJugCard(5, jTextField6.getText());
        Carta carta1 = this.controller.getJugadorCarta(5).get(0);
        Carta carta2 = this.controller.getJugadorCarta(5).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ6C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ6C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom6.setEnabled(false);
        jTextField6.setEnabled(false);
        jButtonEnter6.setEnabled(false);
    }//GEN-LAST:event_jButtonEnter6ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextFieldBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBoardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBoardActionPerformed

    private void jButtonBoardEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBoardEnterActionPerformed
        // TODO add your handling code here:
        controller.enterBoardCard(jTextFieldBoard.getText());
        List<Carta> cartas = controller.getBoardCard();
        JLabel jLabelboards[] = new JLabel[5];
        jLabelboards[0] = jLabelBoardC1;
        jLabelboards[1] = jLabelBoardC2;
        jLabelboards[2] = jLabelBoardC3;
        jLabelboards[3] = jLabelBoardC4;
        jLabelboards[4] = jLabelBoardC5;
        int i = 0;
        for (Carta c : cartas) {
            ImageIcon icon1 = new ImageIcon("img/" + c.toString() + ".png");
            jLabelboards[i].setIcon(resizeImage(icon1.getImage(), 64, 79));
            i++;
        }
        if (cartas.size() == 5) {
            jButtonBoardRandom.setEnabled(false);
            jButtonEnterBoard.setEnabled(false);
            jTextFieldBoard.setEnabled(false);

        }
    }//GEN-LAST:event_jButtonBoardEnterActionPerformed

    private void jButtonBoardRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBoardRandomActionPerformed
        // TODO add your handling code here:
        controller.randomBoardCard();
        List<Carta> cartas = controller.getBoardCard();
        JLabel jLabelboards[] = new JLabel[5];
        jLabelboards[0] = jLabelBoardC1;
        jLabelboards[1] = jLabelBoardC2;
        jLabelboards[2] = jLabelBoardC3;
        jLabelboards[3] = jLabelBoardC4;
        jLabelboards[4] = jLabelBoardC5;
        int i = 0;
        for (Carta c : cartas) {
            ImageIcon icon1 = new ImageIcon("img/" + c.toString() + ".png");
            jLabelboards[i].setIcon(resizeImage(icon1.getImage(), 64, 79));
            i++;
        }
        if (cartas.size() == 5) {
            jButtonBoardRandom.setEnabled(false);
            jButtonEnterBoard.setEnabled(false);
            jTextFieldBoard.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonBoardRandomActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        this.controller.setLogica();
        init();
        //jugador1
        jButtonRandom1.setEnabled(true);
        jTextField1.setEnabled(true);
        jButtonEnter1.setEnabled(true);
        jLabelEquity1.setText("0,00%");
        //jugador2
        jButtonRandom2.setEnabled(true);
        jTextField2.setEnabled(true);
        jButtonEnter2.setEnabled(true);
        jLabelEquity2.setText("0,00%");
        //jugador3
        jButtonRandom3.setEnabled(true);
        jTextField3.setEnabled(true);
        jButtonEnter3.setEnabled(true);
        jLabelEquity3.setText("0,00%");
        //jugador4
        jButtonRandom4.setEnabled(true);
        jTextField4.setEnabled(true);
        jButtonEnter4.setEnabled(true);
        jLabelEquity4.setText("0,00%");
        //jugador5
        jButtonRandom5.setEnabled(true);
        jTextField5.setEnabled(true);
        jButtonEnter5.setEnabled(true);
        jLabelEquity5.setText("0,00%");
        //jugador6
        jButtonRandom6.setEnabled(true);
        jTextField6.setEnabled(true);
        jButtonEnter6.setEnabled(true);
        jLabelEquity6.setText("0,00%");
        //board
        jButtonBoardRandom.setEnabled(true);
        jButtonEnterBoard.setEnabled(true);
        jTextFieldBoard.setEnabled(true);
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculateActionPerformed
        // TODO add your handling code here:
        controller.calcularPuntosJugadores(5 - controller.getBoardCard().size());
        jLabelEquity1.setText(String.format("%.3f", controller.getEquity(0)) + "%");
        jLabelEquity2.setText(String.format("%.3f", controller.getEquity(1)) + "%");
        jLabelEquity3.setText(String.format("%.3f", controller.getEquity(2)) + "%");
        jLabelEquity4.setText(String.format("%.3f", controller.getEquity(3)) + "%");
        jLabelEquity5.setText(String.format("%.3f", controller.getEquity(4)) + "%");
        jLabelEquity6.setText(String.format("%.3f", controller.getEquity(5)) + "%");

        controller.clearAllJugPuntos();
    }//GEN-LAST:event_jButtonCalculateActionPerformed

    private void jButtonFold1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFold1ActionPerformed
        // TODO add your handling code here:
        controller.foldJug(0);
    }//GEN-LAST:event_jButtonFold1ActionPerformed

    private void jButtonFold2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFold2ActionPerformed
        // TODO add your handling code here:
        controller.foldJug(1);
    }//GEN-LAST:event_jButtonFold2ActionPerformed

    private void jButtonFold3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFold3ActionPerformed
        // TODO add your handling code here:
        controller.foldJug(2);
    }//GEN-LAST:event_jButtonFold3ActionPerformed

    private void jButtonFold4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFold4ActionPerformed
        // TODO add your handling code here:
        controller.foldJug(3);
    }//GEN-LAST:event_jButtonFold4ActionPerformed

    private void jButtonFold5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFold5ActionPerformed
        // TODO add your handling code here:
        controller.foldJug(4);
    }//GEN-LAST:event_jButtonFold5ActionPerformed

    private void jButtonFold6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFold6ActionPerformed
        // TODO add your handling code here:
        controller.foldJug(5);
    }//GEN-LAST:event_jButtonFold6ActionPerformed
    private ImageIcon resizeImage(Image image, int width, int height) {

        Image scaledImage = image.getScaledInstance(width, height, Image.SCALE_SMOOTH);

        return new ImageIcon(scaledImage);

    }

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainFrame().setVisible(true);
                MainFrame m = new MainFrame();
                ImageIcon backg = new ImageIcon("img/mesa.jpg");
                JPanel backgroundPanel = new JPanel() {
                    @Override
                    protected void paintComponent(Graphics g) {
                        super.paintComponent(g);
                        // Dibujar la imagen de fondo
                        g.drawImage(backg.getImage(), 0, 0, getWidth(), getHeight(), this);
                    }
                };
                backgroundPanel.setLayout(null);
                m.setContentPane(backgroundPanel);
                //m.setIconImage(new ImageIcon("img/mesa.jpg").getImage());
                m.pack();
                m.setVisible(true);

            }
        });
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton jButtonBoardRandom;
    private javax.swing.JButton jButtonCalculate;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonEnter1;
    private javax.swing.JButton jButtonEnter2;
    private javax.swing.JButton jButtonEnter3;
    private javax.swing.JButton jButtonEnter4;
    private javax.swing.JButton jButtonEnter5;
    private javax.swing.JButton jButtonEnter6;
    private javax.swing.JButton jButtonEnterBoard;
    private javax.swing.JButton jButtonFold1;
    private javax.swing.JButton jButtonFold2;
    private javax.swing.JButton jButtonFold3;
    private javax.swing.JButton jButtonFold4;
    private javax.swing.JButton jButtonFold5;
    private javax.swing.JButton jButtonFold6;
    private javax.swing.JButton jButtonRandom1;
    private javax.swing.JButton jButtonRandom2;
    private javax.swing.JButton jButtonRandom3;
    private javax.swing.JButton jButtonRandom4;
    private javax.swing.JButton jButtonRandom5;
    private javax.swing.JButton jButtonRandom6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBoardC1;
    private javax.swing.JLabel jLabelBoardC2;
    private javax.swing.JLabel jLabelBoardC3;
    private javax.swing.JLabel jLabelBoardC4;
    private javax.swing.JLabel jLabelBoardC5;
    private javax.swing.JLabel jLabelEquity1;
    private javax.swing.JLabel jLabelEquity2;
    private javax.swing.JLabel jLabelEquity3;
    private javax.swing.JLabel jLabelEquity4;
    private javax.swing.JLabel jLabelEquity5;
    private javax.swing.JLabel jLabelEquity6;
    private javax.swing.JLabel jLabelJ1C1;
    private javax.swing.JLabel jLabelJ1C2;
    private javax.swing.JLabel jLabelJ2C1;
    private javax.swing.JLabel jLabelJ2C2;
    private javax.swing.JLabel jLabelJ3C1;
    private javax.swing.JLabel jLabelJ3C2;
    private javax.swing.JLabel jLabelJ4C1;
    private javax.swing.JLabel jLabelJ4C2;
    private javax.swing.JLabel jLabelJ5C1;
    private javax.swing.JLabel jLabelJ5C2;
    private javax.swing.JLabel jLabelJ6C1;
    private javax.swing.JLabel jLabelJ6C2;
    private javax.swing.JLabel jLbelJ1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldBoard;
    // End of variables declaration//GEN-END:variables
}
