package gui;

import controller.Controller;
import java.util.List;
import javax.swing.JLabel;
import java.awt.Image;
import model.*;
import javax.swing.ImageIcon;

public class MainFrame extends javax.swing.JFrame {

    private Controller controller;

    public MainFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelJ6C2 = new javax.swing.JLabel();
        jLabelJ6C1 = new javax.swing.JLabel();
        jLabelEquity6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelJ3C2 = new javax.swing.JLabel();
        jLabelJ3C1 = new javax.swing.JLabel();
        jLabelEquity3 = new javax.swing.JLabel();
        jPanelJ1 = new javax.swing.JPanel();
        jLbelJ1 = new javax.swing.JLabel();
        jLabelJ1C2 = new javax.swing.JLabel();
        jLabelJ1C1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelEquity1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelJ4C2 = new javax.swing.JLabel();
        jLabelJ4C1 = new javax.swing.JLabel();
        jLabelEquity4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabelJ2C2 = new javax.swing.JLabel();
        jLabelJ2C1 = new javax.swing.JLabel();
        jLabelEquity2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelJ5C2 = new javax.swing.JLabel();
        jLabelJ5C1 = new javax.swing.JLabel();
        jLabelEquity5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabelBoardC1 = new javax.swing.JLabel();
        jLabelBoardC2 = new javax.swing.JLabel();
        jLabelBoardC3 = new javax.swing.JLabel();
        jLabelBoardC5 = new javax.swing.JLabel();
        jLabelBoardC4 = new javax.swing.JLabel();
        jButtonRandom1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonEnter1 = new javax.swing.JButton();
        jButtonRandom2 = new javax.swing.JButton();
        jButtonEnter2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonRandom3 = new javax.swing.JButton();
        jButtonEnter3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonRandom4 = new javax.swing.JButton();
        jButtonEnter4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonRandom5 = new javax.swing.JButton();
        jButtonEnter5 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButtonRandom6 = new javax.swing.JButton();
        jButtonEnter6 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldBoard = new javax.swing.JTextField();
        jButtonEnterBoard = new javax.swing.JButton();
        jButtonBoardRandom = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonCalculate = new javax.swing.JButton();
        jButtonFold1 = new javax.swing.JButton();
        jButtonFold2 = new javax.swing.JButton();
        jButtonFold3 = new javax.swing.JButton();
        jButtonFold4 = new javax.swing.JButton();
        jButtonFold5 = new javax.swing.JButton();
        jButtonFold6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jugador6");

        jLabelEquity6.setText("0,00%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabelJ6C1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelJ6C2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabelEquity6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJ6C1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJ6C2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEquity6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel2.setText("jugador3");

        jLabelEquity3.setText("0,00%");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelJ3C1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelJ3C2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelEquity3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJ3C1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJ3C2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEquity3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLbelJ1.setText("jugador1");

        jLabelEquity1.setText("0,00%");

        javax.swing.GroupLayout jPanelJ1Layout = new javax.swing.GroupLayout(jPanelJ1);
        jPanelJ1.setLayout(jPanelJ1Layout);
        jPanelJ1Layout.setHorizontalGroup(
            jPanelJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJ1Layout.createSequentialGroup()
                .addGroup(jPanelJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJ1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel10))
                    .addGroup(jPanelJ1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabelJ1C1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelJ1C2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJ1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJ1Layout.createSequentialGroup()
                        .addComponent(jLabelEquity1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJ1Layout.createSequentialGroup()
                        .addComponent(jLbelJ1)
                        .addGap(87, 87, 87))))
        );
        jPanelJ1Layout.setVerticalGroup(
            jPanelJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJ1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbelJ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJ1C1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJ1C2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEquity1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );

        jLabel4.setText("jugador4");

        jLabelEquity4.setText("0,00%");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabelJ4C1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelJ4C2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelEquity4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJ4C1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJ4C2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEquity4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("jugador2");

        jLabelEquity2.setText("0,00%");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelEquity2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabelJ2C1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelJ2C2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel5)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJ2C1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJ2C2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEquity2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel6.setText("jugador5");

        jLabelEquity5.setText("0,00%");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(70, 92, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabelEquity5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(83, 83, 83))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabelJ5C1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelJ5C2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJ5C1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJ5C2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEquity5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelBoardC1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBoardC2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBoardC3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBoardC4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBoardC5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBoardC4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBoardC3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBoardC5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBoardC1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBoardC2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jButtonRandom1.setText("Random");
        jButtonRandom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandom1ActionPerformed(evt);
            }
        });

        jLabel3.setText("jugador1");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButtonEnter1.setText("Enter");
        jButtonEnter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter1ActionPerformed(evt);
            }
        });

        jButtonRandom2.setText("Random");
        jButtonRandom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandom2ActionPerformed(evt);
            }
        });

        jButtonEnter2.setText("Enter");
        jButtonEnter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter2ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel7.setText("jugador2");

        jButtonRandom3.setText("Random");
        jButtonRandom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandom3ActionPerformed(evt);
            }
        });

        jButtonEnter3.setText("Enter");
        jButtonEnter3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter3ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel8.setText("jugador3");

        jButtonRandom4.setText("Random");
        jButtonRandom4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandom4ActionPerformed(evt);
            }
        });

        jButtonEnter4.setText("Enter");
        jButtonEnter4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter4ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel9.setText("jugador4");

        jButtonRandom5.setText("Random");
        jButtonRandom5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandom5ActionPerformed(evt);
            }
        });

        jButtonEnter5.setText("Enter");
        jButtonEnter5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter5ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel20.setText("jugador5");

        jButtonRandom6.setText("Random");
        jButtonRandom6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandom6ActionPerformed(evt);
            }
        });

        jButtonEnter6.setText("Enter");
        jButtonEnter6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter6ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel21.setText("jugador6");

        jLabel22.setText("board");

        jTextFieldBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBoardActionPerformed(evt);
            }
        });

        jButtonEnterBoard.setText("Enter");
        jButtonEnterBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBoardEnterActionPerformed(evt);
            }
        });

        jButtonBoardRandom.setText("Random");
        jButtonBoardRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBoardRandomActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonCalculate.setText("Calculate");
        jButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculateActionPerformed(evt);
            }
        });

        jButtonFold1.setLabel("fold");
        jButtonFold1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFold1ActionPerformed(evt);
            }
        });

        jButtonFold2.setLabel("fold");
        jButtonFold2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFold2ActionPerformed(evt);
            }
        });

        jButtonFold3.setLabel("fold");
        jButtonFold3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFold3ActionPerformed(evt);
            }
        });

        jButtonFold4.setLabel("fold");
        jButtonFold4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFold4ActionPerformed(evt);
            }
        });

        jButtonFold5.setLabel("fold");
        jButtonFold5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFold5ActionPerformed(evt);
            }
        });

        jButtonFold6.setLabel("fold");
        jButtonFold6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFold6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(544, 544, 544)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEnter3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEnter2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEnter1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRandom2)
                    .addComponent(jButtonRandom1)
                    .addComponent(jButtonRandom3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFold1)
                    .addComponent(jButtonFold2)
                    .addComponent(jButtonFold3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEnter6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRandom6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEnter5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEnter4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRandom5)
                            .addComponent(jButtonRandom4, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFold4)
                    .addComponent(jButtonFold5)
                    .addComponent(jButtonFold6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEnterBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBoardRandom)
                .addGap(394, 394, 394))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(174, 174, 174)))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonRandom1)
                                    .addComponent(jButtonEnter1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jButtonFold1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButtonRandom2)
                                            .addComponent(jButtonEnter2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonFold2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButtonRandom3)
                                            .addComponent(jButtonEnter3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonFold3)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonRandom4)
                                    .addComponent(jButtonEnter4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jButtonFold4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonRandom5)
                                    .addComponent(jButtonEnter5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addComponent(jButtonFold5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonRandom6)
                                    .addComponent(jButtonEnter6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)
                                    .addComponent(jButtonFold6))))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBoardRandom)
                    .addComponent(jButtonEnterBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        ImageIcon icon = new ImageIcon("img/back.png");
        jLabelJ1C1.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ1C2.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ2C1.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ2C2.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ3C1.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ3C2.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ4C1.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ4C2.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ5C1.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ5C2.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ6C1.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelJ6C2.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelBoardC1.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelBoardC2.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelBoardC3.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelBoardC4.setIcon(resizeImage(icon.getImage(), 64, 79));
        jLabelBoardC5.setIcon(resizeImage(icon.getImage(), 64, 79));
    }
    private void jButtonRandom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandom1ActionPerformed
        // TODO add your handling code here:
        this.controller.randomJugCard(0);
        List<Carta> carta = this.controller.getJugadorCarta(0);
        ImageIcon icon1 = new ImageIcon("img/" + carta.get(0).toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta.get(1).toString() + ".png");

        jLabelJ1C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ1C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom1.setEnabled(false);
        jTextField1.setEnabled(false);
        jButtonEnter1.setEnabled(false);
    }//GEN-LAST:event_jButtonRandom1ActionPerformed

    private void jButtonEnter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter1ActionPerformed
        // TODO add your handling code here:
        controller.enterJugCard(0, jTextField1.getText());
        Carta carta1 = this.controller.getJugadorCarta(0).get(0);
        Carta carta2 = this.controller.getJugadorCarta(0).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ1C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ1C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom1.setEnabled(false);
        jTextField1.setEnabled(false);
        jButtonEnter1.setEnabled(false);

    }//GEN-LAST:event_jButtonEnter1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonRandom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandom2ActionPerformed
        // TODO add your handling code here:
        this.controller.randomJugCard(1);
        Carta carta1 = this.controller.getJugadorCarta(1).get(0);
        Carta carta2 = this.controller.getJugadorCarta(1).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ2C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ2C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom2.setEnabled(false);
        jTextField2.setEnabled(false);
        jButtonEnter2.setEnabled(false);
    }//GEN-LAST:event_jButtonRandom2ActionPerformed

    private void jButtonEnter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter2ActionPerformed
        // TODO add your handling code here:
        controller.enterJugCard(1, jTextField2.getText());
        Carta carta1 = this.controller.getJugadorCarta(1).get(0);
        Carta carta2 = this.controller.getJugadorCarta(1).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ2C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ2C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom2.setEnabled(false);
        jTextField2.setEnabled(false);
        jButtonEnter2.setEnabled(false);
    }//GEN-LAST:event_jButtonEnter2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButtonRandom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandom3ActionPerformed
        // TODO add your handling code here:
        this.controller.randomJugCard(2);
        Carta carta1 = this.controller.getJugadorCarta(2).get(0);
        Carta carta2 = this.controller.getJugadorCarta(2).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ3C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ3C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom3.setEnabled(false);
        jTextField3.setEnabled(false);
        jButtonEnter3.setEnabled(false);
    }//GEN-LAST:event_jButtonRandom3ActionPerformed

    private void jButtonEnter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter3ActionPerformed
        // TODO add your handling code here:
        controller.enterJugCard(2, jTextField3.getText());
        Carta carta1 = this.controller.getJugadorCarta(2).get(0);
        Carta carta2 = this.controller.getJugadorCarta(2).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ3C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ3C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom3.setEnabled(false);
        jTextField3.setEnabled(false);
        jButtonEnter3.setEnabled(false);
    }//GEN-LAST:event_jButtonEnter3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButtonRandom4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandom4ActionPerformed
        // TODO add your handling code here:
        this.controller.randomJugCard(3);
        Carta carta1 = this.controller.getJugadorCarta(3).get(0);
        Carta carta2 = this.controller.getJugadorCarta(3).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ4C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ4C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom4.setEnabled(false);
        jTextField4.setEnabled(false);
        jButtonEnter4.setEnabled(false);
    }//GEN-LAST:event_jButtonRandom4ActionPerformed

    private void jButtonEnter4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter4ActionPerformed
        // TODO add your handling code here:
        controller.enterJugCard(3, jTextField4.getText());
        Carta carta1 = this.controller.getJugadorCarta(3).get(0);
        Carta carta2 = this.controller.getJugadorCarta(3).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ4C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ4C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom4.setEnabled(false);
        jTextField4.setEnabled(false);
        jButtonEnter4.setEnabled(false);
    }//GEN-LAST:event_jButtonEnter4ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButtonRandom5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandom5ActionPerformed
        // TODO add your handling code here:
        this.controller.randomJugCard(4);
        Carta carta1 = this.controller.getJugadorCarta(4).get(0);
        Carta carta2 = this.controller.getJugadorCarta(4).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ5C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ5C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom5.setEnabled(false);
        jTextField5.setEnabled(false);
        jButtonEnter5.setEnabled(false);
    }//GEN-LAST:event_jButtonRandom5ActionPerformed

    private void jButtonEnter5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter5ActionPerformed
        // TODO add your handling code here:
        controller.enterJugCard(4, jTextField5.getText());
        Carta carta1 = this.controller.getJugadorCarta(4).get(0);
        Carta carta2 = this.controller.getJugadorCarta(4).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ5C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ5C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom5.setEnabled(false);
        jTextField5.setEnabled(false);
        jButtonEnter5.setEnabled(false);
    }//GEN-LAST:event_jButtonEnter5ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButtonRandom6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandom6ActionPerformed
        // TODO add your handling code here:
        this.controller.randomJugCard(5);
        Carta carta1 = this.controller.getJugadorCarta(5).get(0);
        Carta carta2 = this.controller.getJugadorCarta(5).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ6C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ6C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom6.setEnabled(false);
        jTextField6.setEnabled(false);
        jButtonEnter6.setEnabled(false);
    }//GEN-LAST:event_jButtonRandom6ActionPerformed

    private void jButtonEnter6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter6ActionPerformed
        // TODO add your handling code here:
        controller.enterJugCard(5, jTextField6.getText());
        Carta carta1 = this.controller.getJugadorCarta(5).get(0);
        Carta carta2 = this.controller.getJugadorCarta(5).get(1);
        ImageIcon icon1 = new ImageIcon("img/" + carta1.toString() + ".png");
        ImageIcon icon2 = new ImageIcon("img/" + carta2.toString() + ".png");

        jLabelJ6C1.setIcon(resizeImage(icon1.getImage(), 64, 79));
        jLabelJ6C2.setIcon(resizeImage(icon2.getImage(), 64, 79));
        jButtonRandom6.setEnabled(false);
        jTextField6.setEnabled(false);
        jButtonEnter6.setEnabled(false);
    }//GEN-LAST:event_jButtonEnter6ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextFieldBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBoardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBoardActionPerformed

    private void jButtonBoardEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBoardEnterActionPerformed
        // TODO add your handling code here:
        controller.enterBoardCard(jTextFieldBoard.getText());
        List<Carta> cartas = controller.getBoardCard();
        JLabel jLabelboards[] = new JLabel[5];
        jLabelboards[0] = jLabelBoardC1;
        jLabelboards[1] = jLabelBoardC2;
        jLabelboards[2] = jLabelBoardC3;
        jLabelboards[3] = jLabelBoardC4;
        jLabelboards[4] = jLabelBoardC5;
        int i = 0;
        for (Carta c : cartas) {
            ImageIcon icon1 = new ImageIcon("img/" + c.toString() + ".png");
            jLabelboards[i].setIcon(resizeImage(icon1.getImage(), 64, 79));
            i++;
        }
        if (cartas.size() == 5) {
            jButtonBoardRandom.setEnabled(false);
            jButtonEnterBoard.setEnabled(false);
            jTextFieldBoard.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonBoardEnterActionPerformed

    private void jButtonBoardRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBoardRandomActionPerformed
        // TODO add your handling code here:
        controller.randomBoardCard();
        List<Carta> cartas = controller.getBoardCard();
        JLabel jLabelboards[] = new JLabel[5];
        jLabelboards[0] = jLabelBoardC1;
        jLabelboards[1] = jLabelBoardC2;
        jLabelboards[2] = jLabelBoardC3;
        jLabelboards[3] = jLabelBoardC4;
        jLabelboards[4] = jLabelBoardC5;
        int i = 0;
        for (Carta c : cartas) {
            ImageIcon icon1 = new ImageIcon("img/" + c.toString() + ".png");
            jLabelboards[i].setIcon(resizeImage(icon1.getImage(), 64, 79));
            i++;
        }
        if (cartas.size() == 5) {
            jButtonBoardRandom.setEnabled(false);
            jButtonEnterBoard.setEnabled(false);
            jTextFieldBoard.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonBoardRandomActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        this.controller.setLogica();
        init();
        //jugador1
        jButtonRandom1.setEnabled(true);
        jTextField1.setEnabled(true);
        jButtonEnter1.setEnabled(true);
        jLabelEquity1.setText("0,00%");
        //jugador2
        jButtonRandom2.setEnabled(true);
        jTextField2.setEnabled(true);
        jButtonEnter2.setEnabled(true);
        jLabelEquity2.setText("0,00%");
        //jugador3
        jButtonRandom3.setEnabled(true);
        jTextField3.setEnabled(true);
        jButtonEnter3.setEnabled(true);
        jLabelEquity3.setText("0,00%");
        //jugador4
        jButtonRandom4.setEnabled(true);
        jTextField4.setEnabled(true);
        jButtonEnter4.setEnabled(true);
        jLabelEquity4.setText("0,00%");
        //jugador5
        jButtonRandom5.setEnabled(true);
        jTextField5.setEnabled(true);
        jButtonEnter5.setEnabled(true);
        jLabelEquity5.setText("0,00%");
        //jugador6
        jButtonRandom6.setEnabled(true);
        jTextField6.setEnabled(true);
        jButtonEnter6.setEnabled(true);
        jLabelEquity6.setText("0,00%");
        //board
        jButtonBoardRandom.setEnabled(true);
        jButtonEnterBoard.setEnabled(true);
        jTextFieldBoard.setEnabled(true);
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculateActionPerformed
        // TODO add your handling code here:
        controller.calcularPuntosJugadores(5 - controller.getBoardCard().size());
        jLabelEquity1.setText(String.format("%.3f",controller.getEquity(0))+ "%");
        jLabelEquity2.setText(String.format("%.3f",controller.getEquity(1))+ "%");
        jLabelEquity3.setText(String.format("%.3f",controller.getEquity(2))+ "%");
        jLabelEquity4.setText(String.format("%.3f",controller.getEquity(3))+ "%");
        jLabelEquity5.setText(String.format("%.3f",controller.getEquity(4))+ "%");
        jLabelEquity6.setText(String.format("%.3f",controller.getEquity(5))+ "%");

        controller.clearAllJugPuntos();
    }//GEN-LAST:event_jButtonCalculateActionPerformed

    private void jButtonFold1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFold1ActionPerformed
        // TODO add your handling code here:
        controller.foldJug(0);
    }//GEN-LAST:event_jButtonFold1ActionPerformed

    private void jButtonFold2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFold2ActionPerformed
        // TODO add your handling code here:
        controller.foldJug(1);
    }//GEN-LAST:event_jButtonFold2ActionPerformed

    private void jButtonFold3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFold3ActionPerformed
        // TODO add your handling code here:
        controller.foldJug(2);
    }//GEN-LAST:event_jButtonFold3ActionPerformed

    private void jButtonFold4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFold4ActionPerformed
        // TODO add your handling code here:
        controller.foldJug(3);
    }//GEN-LAST:event_jButtonFold4ActionPerformed

    private void jButtonFold5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFold5ActionPerformed
        // TODO add your handling code here:
        controller.foldJug(4);
    }//GEN-LAST:event_jButtonFold5ActionPerformed

    private void jButtonFold6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFold6ActionPerformed
        // TODO add your handling code here:
        controller.foldJug(5);
    }//GEN-LAST:event_jButtonFold6ActionPerformed
    private ImageIcon resizeImage(Image image, int width, int height) {

        Image scaledImage = image.getScaledInstance(width, height, Image.SCALE_SMOOTH);

        return new ImageIcon(scaledImage);

    }

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBoardRandom;
    private javax.swing.JButton jButtonCalculate;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonEnter1;
    private javax.swing.JButton jButtonEnter2;
    private javax.swing.JButton jButtonEnter3;
    private javax.swing.JButton jButtonEnter4;
    private javax.swing.JButton jButtonEnter5;
    private javax.swing.JButton jButtonEnter6;
    private javax.swing.JButton jButtonEnterBoard;
    private javax.swing.JButton jButtonFold1;
    private javax.swing.JButton jButtonFold2;
    private javax.swing.JButton jButtonFold3;
    private javax.swing.JButton jButtonFold4;
    private javax.swing.JButton jButtonFold5;
    private javax.swing.JButton jButtonFold6;
    private javax.swing.JButton jButtonRandom1;
    private javax.swing.JButton jButtonRandom2;
    private javax.swing.JButton jButtonRandom3;
    private javax.swing.JButton jButtonRandom4;
    private javax.swing.JButton jButtonRandom5;
    private javax.swing.JButton jButtonRandom6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBoardC1;
    private javax.swing.JLabel jLabelBoardC2;
    private javax.swing.JLabel jLabelBoardC3;
    private javax.swing.JLabel jLabelBoardC4;
    private javax.swing.JLabel jLabelBoardC5;
    private javax.swing.JLabel jLabelEquity1;
    private javax.swing.JLabel jLabelEquity2;
    private javax.swing.JLabel jLabelEquity3;
    private javax.swing.JLabel jLabelEquity4;
    private javax.swing.JLabel jLabelEquity5;
    private javax.swing.JLabel jLabelEquity6;
    private javax.swing.JLabel jLabelJ1C1;
    private javax.swing.JLabel jLabelJ1C2;
    private javax.swing.JLabel jLabelJ2C1;
    private javax.swing.JLabel jLabelJ2C2;
    private javax.swing.JLabel jLabelJ3C1;
    private javax.swing.JLabel jLabelJ3C2;
    private javax.swing.JLabel jLabelJ4C1;
    private javax.swing.JLabel jLabelJ4C2;
    private javax.swing.JLabel jLabelJ5C1;
    private javax.swing.JLabel jLabelJ5C2;
    private javax.swing.JLabel jLabelJ6C1;
    private javax.swing.JLabel jLabelJ6C2;
    private javax.swing.JLabel jLbelJ1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelJ1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldBoard;
    // End of variables declaration//GEN-END:variables
}
